
name: Publish 

on:
  pull_request:
    branches: [ "main", "development" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./towing-drivers-microservice.sln

      - name: Build
        run: dotnet build ./towing-drivers-microservice.sln --configuration Release --no-restore

      - name: Publish 
        run: dotnet publish ./towing-drivers-microservice.sln --configuration Release --no-build